import AuthProvider from "../context/AuthProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <AuthProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Nav />
            {children}
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
